id: P1A58F237
initial_creation_type: input
source_metadata:
  title: Jetsün Drakpa Gyaltsen Series
  language: pt
  description: 'Texts by the great Sakya patriarch Jetsün Drakpa Gyaltsen (rje btsun
    grags pa rgyal mtshan, 1147–1216):'
  volume:
    b3093561581240d6b0283c76f53d5e7d:
      title: On Jetsün Drakpa Gyaltsen’s How to Take the Practice to Heart
      parent: Commentaries
    2ac62efc9e45408e9f7a26b4389211f5:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Mañjuśrī
    12fb785ba65e4a38aa265442a6ea59c9:
      title: Parting from the Four Attachments
      parent: Mind Training
    303333f717c04e4fbe40d3c3fec6f39d:
      title: Short Maṇḍala Offering
      parent: Offering
    ef56fa63df1847c0bc28763ecb2b3186:
      title: How to Take the Practice to Heart
      parent: Songs
    3b741b58eb6146819b8cb11989429808:
      title: An Outline of The Praise to Tārā with Twenty-One Verses of Homage
      parent: Tārā
    440bcf388dea425ca092631287550631:
      title: 'Brilliant Rays of Light: A Commentary on the Praise to Tārā'
      parent: Tārā
    60e6ad9515e74ccd9241253882685792:
      title: Prayer to Jetsün Tārā
      parent: Tārā
created_at: '2022-03-01T00:01:07.269169'
last_modified_at: '2022-03-01T00:01:07.269172'
